[package]
name = "zngur-autozng"
description = "Generating Zngur zng files automatically for a Rust crate"
version = "0.6.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
