[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xshell = "0.2.5"
anyhow = "1.0"
clap = { version = "4.4.2", features = ["derive"] }
