[package]
name = "zngur-parser"
description = "Parser of the zng file"
readme = "../README.md"
version = "0.11.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = { workspace = true }
ariadne = { workspace = true }
itertools = { workspace = true }
strip-ansi-escapes = { workspace = true }
chumsky = { version = "=1.0.0-alpha.8", features = [] }
zngur-def = { version = "=0.11.0", path = "../zngur-def" }

[dev-dependencies]
expect-test = { workspace = true }
