[package]
name = "example-memory_management"
version = "0.2.1"
edition.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
