name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - book/**
      - .github/workflows/site.yml
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/install@mdbook
      - run: mdbook --version

      - name: Build
        run: |
          cd book
          mdbook build
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: book/book
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
